// <auto-generated />
using System;
using Lykke.Service.EncryptedFileStorage.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lykke.Service.EncryptedFileStorage.MsSqlRepositories.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("encrypted_files_storage")
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lykke.Service.EncryptedFileStorage.Domain.Models.EncryptedFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("BlobName")
                        .HasMaxLength(1024);

                    b.Property<DateTime?>("FileDate");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<bool>("IsUploadCompleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<long?>("Length");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(63);

                    b.HasKey("FileId");

                    b.HasIndex("Origin", "FileName")
                        .IsUnique();

                    b.ToTable("encrypted_files");
                });
#pragma warning restore 612, 618
        }
    }
}
